[package]
name = "cornedbeef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8", default-features = false }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "bench"
harness = false
